--
-- PostgreSQL database dump
--


-- Dumped from database version 18.4
-- Dumped by pg_dump version 18.4

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: account; Type: SCHEMA; Schema: -; Owner: -
--

CREATE SCHEMA account;


--
-- Name: common; Type: SCHEMA; Schema: -; Owner: -
--

CREATE SCHEMA common;


--
-- Name: log; Type: SCHEMA; Schema: -; Owner: -
--

CREATE SCHEMA log;


--
-- Name: player; Type: SCHEMA; Schema: -; Owner: -
--

CREATE SCHEMA player;


--
-- Name: world; Type: SCHEMA; Schema: -; Owner: -
--

CREATE SCHEMA world;


--
-- Name: pgcrypto; Type: EXTENSION; Schema: -; Owner: -
--

CREATE EXTENSION IF NOT EXISTS pgcrypto WITH SCHEMA account;


--
-- Name: EXTENSION pgcrypto; Type: COMMENT; Schema: -; Owner: -
--

COMMENT ON EXTENSION pgcrypto IS 'cryptographic functions';


--
-- Name: mysql_hash_password(text); Type: FUNCTION; Schema: account; Owner: -
--

CREATE FUNCTION account.mysql_hash_password(pw text) RETURNS text
    LANGUAGE sql IMMUTABLE STRICT
    AS $$
  SELECT '*' || upper(encode(digest(digest(pw::bytea,'sha1'),'sha1'),'hex'))
$$;


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: account; Type: TABLE; Schema: account; Owner: -
--

CREATE TABLE account.account (
    id bigint NOT NULL,
    login character varying(16) DEFAULT ''::character varying NOT NULL,
    password character varying(42) DEFAULT ''::character varying NOT NULL,
    social_id character varying(7) DEFAULT ''::character varying NOT NULL,
    email character varying(100) DEFAULT ''::character varying NOT NULL,
    securitycode character varying(192) DEFAULT ''::character varying NOT NULL,
    status character varying(8) DEFAULT 'OK'::character varying NOT NULL,
    lang character varying(4) DEFAULT 'es'::character varying NOT NULL,
    availdt timestamp without time zone DEFAULT now() NOT NULL,
    create_time timestamp without time zone DEFAULT now() NOT NULL,
    last_play timestamp without time zone DEFAULT now() NOT NULL,
    gold_expire timestamp without time zone DEFAULT now() NOT NULL,
    silver_expire timestamp without time zone DEFAULT now() NOT NULL,
    safebox_expire timestamp without time zone DEFAULT now() NOT NULL,
    autoloot_expire timestamp without time zone DEFAULT now() NOT NULL,
    fish_mind_expire timestamp without time zone DEFAULT now() NOT NULL,
    marriage_fast_expire timestamp without time zone DEFAULT now() NOT NULL,
    money_drop_rate_expire timestamp without time zone DEFAULT now() NOT NULL,
    real_name character varying(16) DEFAULT ''::character varying,
    question1 character varying(56) DEFAULT NULL::character varying,
    answer1 character varying(56) DEFAULT NULL::character varying,
    question2 character varying(56) DEFAULT NULL::character varying,
    answer2 character varying(56) DEFAULT NULL::character varying,
    cash integer DEFAULT 0,
    mileage integer DEFAULT 0,
    hwid character varying(64) DEFAULT ''::character varying NOT NULL
);


--
-- Name: COLUMN account.login; Type: COMMENT; Schema: account; Owner: -
--

COMMENT ON COLUMN account.account.login IS 'LOGIN_MAX_LEN=30';


--
-- Name: COLUMN account.password; Type: COMMENT; Schema: account; Owner: -
--

COMMENT ON COLUMN account.account.password IS 'PASSWD_MAX_LEN=16; default 45 size';


--
-- Name: account_id_seq; Type: SEQUENCE; Schema: account; Owner: -
--

ALTER TABLE account.account ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME account.account_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: exp_table; Type: TABLE; Schema: common; Owner: -
--

CREATE TABLE common.exp_table (
    level bigint NOT NULL,
    exp bigint DEFAULT 0 NOT NULL
);


--
-- Name: exp_table_level_seq; Type: SEQUENCE; Schema: common; Owner: -
--

ALTER TABLE common.exp_table ALTER COLUMN level ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME common.exp_table_level_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: gmhost; Type: TABLE; Schema: common; Owner: -
--

CREATE TABLE common.gmhost (
    mip character varying(16) DEFAULT ''::character varying NOT NULL
);


--
-- Name: gmlist; Type: TABLE; Schema: common; Owner: -
--

CREATE TABLE common.gmlist (
    mid bigint NOT NULL,
    maccount character varying(16) DEFAULT ''::character varying NOT NULL,
    mname character varying(16) DEFAULT ''::character varying NOT NULL,
    mcontactip character varying(16) DEFAULT ''::character varying NOT NULL,
    mserverip character varying(16) DEFAULT 'ALL'::character varying NOT NULL,
    mauthority text DEFAULT 'PLAYER'::text NOT NULL,
    CONSTRAINT gmlist_mauthority_check CHECK ((mauthority = ANY (ARRAY['IMPLEMENTOR'::text, 'HIGH_WIZARD'::text, 'GOD'::text, 'LOW_WIZARD'::text, 'PLAYER'::text])))
);


--
-- Name: gmlist_mid_seq; Type: SEQUENCE; Schema: common; Owner: -
--

ALTER TABLE common.gmlist ALTER COLUMN mid ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME common.gmlist_mid_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: item_descriptions; Type: TABLE; Schema: common; Owner: -
--

CREATE TABLE common.item_descriptions (
    vnum bigint NOT NULL,
    lang character varying(4) NOT NULL,
    text text NOT NULL
);


--
-- Name: item_icons; Type: TABLE; Schema: common; Owner: -
--

CREATE TABLE common.item_icons (
    vnum bigint NOT NULL,
    png bytea NOT NULL
);


--
-- Name: item_names; Type: TABLE; Schema: common; Owner: -
--

CREATE TABLE common.item_names (
    vnum bigint NOT NULL,
    lang character varying(4) NOT NULL,
    name text NOT NULL
);


--
-- Name: locale; Type: TABLE; Schema: common; Owner: -
--

CREATE TABLE common.locale (
    mkey character varying(255) DEFAULT ''::character varying NOT NULL,
    mvalue character varying(255) DEFAULT ''::character varying NOT NULL
);


--
-- Name: map_names; Type: TABLE; Schema: common; Owner: -
--

CREATE TABLE common.map_names (
    map_id integer NOT NULL,
    lang character varying(4) NOT NULL,
    name text NOT NULL
);


--
-- Name: message_texts; Type: TABLE; Schema: common; Owner: -
--

CREATE TABLE common.message_texts (
    key text NOT NULL,
    lang character varying(4) NOT NULL,
    value text NOT NULL
);


--
-- Name: mob_names; Type: TABLE; Schema: common; Owner: -
--

CREATE TABLE common.mob_names (
    vnum bigint NOT NULL,
    lang character varying(4) NOT NULL,
    name text NOT NULL
);


--
-- Name: priv_settings; Type: TABLE; Schema: common; Owner: -
--

CREATE TABLE common.priv_settings (
    priv_type text DEFAULT 'EMPIRE'::text NOT NULL,
    id bigint DEFAULT 0 NOT NULL,
    type bigint DEFAULT 4 NOT NULL,
    value integer DEFAULT 0 NOT NULL,
    duration timestamp without time zone DEFAULT now() NOT NULL,
    CONSTRAINT priv_settings_priv_type_check CHECK ((priv_type = ANY (ARRAY['PLAYER'::text, 'GUILD'::text, 'EMPIRE'::text])))
);


--
-- Name: COLUMN priv_settings.priv_type; Type: COMMENT; Schema: common; Owner: -
--

COMMENT ON COLUMN common.priv_settings.priv_type IS 'GUILD and PLAYER are untested.';


--
-- Name: COLUMN priv_settings.id; Type: COMMENT; Schema: common; Owner: -
--

COMMENT ON COLUMN common.priv_settings.id IS 'this is for empire_id, player_id or guild_id';


--
-- Name: COLUMN priv_settings.type; Type: COMMENT; Schema: common; Owner: -
--

COMMENT ON COLUMN common.priv_settings.type IS '1:item_drop, 2:gold_drop, 3:gold10_drop, 4:exp (1~4)';


--
-- Name: COLUMN priv_settings.value; Type: COMMENT; Schema: common; Owner: -
--

COMMENT ON COLUMN common.priv_settings.value IS '0~1000%';


--
-- Name: skill_names; Type: TABLE; Schema: common; Owner: -
--

CREATE TABLE common.skill_names (
    skill_id integer NOT NULL,
    lang character varying(4) NOT NULL,
    name text NOT NULL
);


--
-- Name: spam_db; Type: TABLE; Schema: common; Owner: -
--

CREATE TABLE common.spam_db (
    word character varying(255) NOT NULL,
    score integer DEFAULT 1 NOT NULL,
    type text DEFAULT 'SPAM'::text NOT NULL,
    CONSTRAINT spam_db_type_check CHECK ((type = ANY (ARRAY['SPAM'::text, 'MAPS'::text])))
);


--
-- Name: ui_texts; Type: TABLE; Schema: common; Owner: -
--

CREATE TABLE common.ui_texts (
    key text NOT NULL,
    lang character varying(4) NOT NULL,
    value text NOT NULL
);


--
-- Name: acce; Type: TABLE; Schema: log; Owner: -
--

CREATE TABLE log.acce (
    pid integer NOT NULL,
    "time" timestamp without time zone NOT NULL,
    x integer NOT NULL,
    y integer NOT NULL,
    item_vnum integer NOT NULL,
    item_uid integer NOT NULL,
    item_count smallint NOT NULL,
    item_abs_chance smallint NOT NULL,
    success bytea NOT NULL
);


--
-- Name: bootlog; Type: TABLE; Schema: log; Owner: -
--

CREATE TABLE log.bootlog (
    "time" timestamp without time zone,
    hostname bytea,
    channel integer
);


--
-- Name: change_empire; Type: TABLE; Schema: log; Owner: -
--

CREATE TABLE log.change_empire (
    account_id bigint DEFAULT 0 NOT NULL,
    change_count integer,
    data timestamp without time zone
);


--
-- Name: change_name; Type: TABLE; Schema: log; Owner: -
--

CREATE TABLE log.change_name (
    pid bigint,
    old_name bytea,
    new_name bytea,
    "time" timestamp without time zone,
    ip bytea
);


--
-- Name: chat_log; Type: TABLE; Schema: log; Owner: -
--

CREATE TABLE log.chat_log (
    "where" bigint NOT NULL,
    who_id bigint NOT NULL,
    who_name character varying(25) NOT NULL,
    whom_id bigint,
    whom_name character varying(25) DEFAULT NULL::character varying,
    type text NOT NULL,
    msg bytea NOT NULL,
    "when" timestamp without time zone DEFAULT now() NOT NULL,
    ip character varying(15) NOT NULL,
    CONSTRAINT chat_log_type_check CHECK ((type = ANY (ARRAY['NORMAL'::text, 'WHISPER'::text, 'PARTY'::text, 'GUILD'::text])))
);


--
-- Name: command_log; Type: TABLE; Schema: log; Owner: -
--

CREATE TABLE log.command_log (
    userid bigint,
    server integer DEFAULT 999,
    ip bytea,
    port bigint,
    username bytea,
    command bytea,
    date timestamp without time zone
);


--
-- Name: cube; Type: TABLE; Schema: log; Owner: -
--

CREATE TABLE log.cube (
    pid bigint,
    "time" timestamp without time zone,
    x bigint,
    y bigint,
    item_vnum bigint,
    item_uid bigint,
    item_count integer,
    success integer
);


--
-- Name: dragon_slay_log; Type: TABLE; Schema: log; Owner: -
--

CREATE TABLE log.dragon_slay_log (
    guild_id bigint NOT NULL,
    vnum bigint NOT NULL,
    start_time timestamp without time zone DEFAULT now() NOT NULL,
    end_time timestamp without time zone DEFAULT now() NOT NULL
);


--
-- Name: fish_log; Type: TABLE; Schema: log; Owner: -
--

CREATE TABLE log.fish_log (
    "time" timestamp without time zone DEFAULT now() NOT NULL,
    player_id bigint DEFAULT 0 NOT NULL,
    map_index smallint DEFAULT 0 NOT NULL,
    fish_id bigint DEFAULT 0 NOT NULL,
    fishing_level integer DEFAULT 0 NOT NULL,
    waiting_time integer DEFAULT 0 NOT NULL,
    success smallint DEFAULT 0 NOT NULL,
    size smallint DEFAULT 0 NOT NULL
);


--
-- Name: gametimelog; Type: TABLE; Schema: log; Owner: -
--

CREATE TABLE log.gametimelog (
    login bytea,
    type bigint,
    logon_time timestamp without time zone,
    logout_time timestamp without time zone,
    use_time bigint,
    ip bytea,
    server bytea
);


--
-- Name: goldlog; Type: TABLE; Schema: log; Owner: -
--

CREATE TABLE log.goldlog (
    date date,
    "time" time without time zone,
    pid bigint,
    what bigint,
    how bytea,
    hint bytea
);


--
-- Name: COLUMN goldlog.how; Type: COMMENT; Schema: log; Owner: -
--

COMMENT ON COLUMN log.goldlog.how IS 'contains: QUEST, BUY, SELL, SHOP_BUY, SHOP_SELL, EXCHANGE_TAKE, EXCHANGE_GIVE';


--
-- Name: hack_crc_log; Type: TABLE; Schema: log; Owner: -
--

CREATE TABLE log.hack_crc_log (
    "time" timestamp without time zone,
    login bytea,
    name bytea,
    ip bytea,
    server bytea,
    why bytea,
    crc bigint
);


--
-- Name: hack_log; Type: TABLE; Schema: log; Owner: -
--

CREATE TABLE log.hack_log (
    "time" timestamp without time zone,
    login bytea,
    name bytea,
    ip bytea,
    server bytea,
    why bytea
);


--
-- Name: hackshield_log; Type: TABLE; Schema: log; Owner: -
--

CREATE TABLE log.hackshield_log (
    "time" timestamp without time zone,
    account_id bigint,
    login bytea,
    pid bigint,
    name bytea,
    reason bigint,
    ip bigint
);


--
-- Name: COLUMN hackshield_log.ip; Type: COMMENT; Schema: log; Owner: -
--

COMMENT ON COLUMN log.hackshield_log.ip IS 'inet_aton(''''%s'''')';


--
-- Name: invalid_server_log; Type: TABLE; Schema: log; Owner: -
--

CREATE TABLE log.invalid_server_log (
    locale_type bigint,
    log_date timestamp without time zone,
    ip bytea,
    revision bytea
);


--
-- Name: levellog; Type: TABLE; Schema: log; Owner: -
--

CREATE TABLE log.levellog (
    name bytea,
    level bigint,
    "time" timestamp without time zone,
    account_id bigint,
    pid bigint,
    playtime integer
);


--
-- Name: COLUMN levellog.pid; Type: COMMENT; Schema: log; Owner: -
--

COMMENT ON COLUMN log.levellog.pid IS 'contains REPLACE query!';


--
-- Name: log; Type: TABLE; Schema: log; Owner: -
--

CREATE TABLE log.log (
    type bytea,
    "time" timestamp without time zone,
    who bigint,
    x bigint,
    y bigint,
    what numeric(20,0) DEFAULT NULL::numeric,
    how bytea,
    hint bytea,
    ip bytea,
    vnum bigint
);


--
-- Name: COLUMN log.type; Type: COMMENT; Schema: log; Owner: -
--

COMMENT ON COLUMN log.log.type IS 'contains: CHARACTER, ITEM';


--
-- Name: COLUMN log.hint; Type: COMMENT; Schema: log; Owner: -
--

COMMENT ON COLUMN log.log.hint IS 'snprintf with 80u size';


--
-- Name: loginlog; Type: TABLE; Schema: log; Owner: -
--

CREATE TABLE log.loginlog (
    type bytea,
    "time" timestamp without time zone,
    channel integer,
    account_id bigint,
    pid bigint,
    level integer,
    job integer,
    playtime bigint
);


--
-- Name: COLUMN loginlog.type; Type: COMMENT; Schema: log; Owner: -
--

COMMENT ON COLUMN log.loginlog.type IS 'contains: LOGIN, LOGOUT';


--
-- Name: loginlog2; Type: TABLE; Schema: log; Owner: -
--

CREATE TABLE log.loginlog2 (
    type bytea,
    is_gm bytea,
    login_time timestamp without time zone,
    channel integer,
    account_id bigint,
    pid bigint,
    ip bigint,
    client_version bytea,
    logout_time timestamp without time zone,
    playtime timestamp without time zone,
    id integer
);


--
-- Name: COLUMN loginlog2.type; Type: COMMENT; Schema: log; Owner: -
--

COMMENT ON COLUMN log.loginlog2.type IS 'contains: VALID, INVALID';


--
-- Name: COLUMN loginlog2.is_gm; Type: COMMENT; Schema: log; Owner: -
--

COMMENT ON COLUMN log.loginlog2.is_gm IS 'contains: Y, N';


--
-- Name: COLUMN loginlog2.ip; Type: COMMENT; Schema: log; Owner: -
--

COMMENT ON COLUMN log.loginlog2.ip IS 'inet_aton(''''%s'''')';


--
-- Name: COLUMN loginlog2.client_version; Type: COMMENT; Schema: log; Owner: -
--

COMMENT ON COLUMN log.loginlog2.client_version IS 'maybe 1215955205';


--
-- Name: COLUMN loginlog2.id; Type: COMMENT; Schema: log; Owner: -
--

COMMENT ON COLUMN log.loginlog2.id IS 'maybe primary';


--
-- Name: money_log; Type: TABLE; Schema: log; Owner: -
--

CREATE TABLE log.money_log (
    "time" timestamp without time zone,
    type integer,
    vnum integer,
    gold integer
);


--
-- Name: mutation_audit; Type: TABLE; Schema: log; Owner: -
--

CREATE TABLE log.mutation_audit (
    mutation_id uuid NOT NULL,
    applied_at timestamp with time zone DEFAULT now() NOT NULL,
    payload text NOT NULL
);


--
-- Name: pcbang_loginlog; Type: TABLE; Schema: log; Owner: -
--

CREATE TABLE log.pcbang_loginlog (
    "time" timestamp without time zone,
    pcbang_id bigint,
    ip bytea,
    pid bigint,
    play_time bigint
);


--
-- Name: quest_reward_log; Type: TABLE; Schema: log; Owner: -
--

CREATE TABLE log.quest_reward_log (
    quest_name bytea,
    pid bigint,
    level bigint,
    type integer,
    how bigint,
    hint bigint,
    "when" timestamp without time zone
);


--
-- Name: COLUMN quest_reward_log.type; Type: COMMENT; Schema: log; Owner: -
--

COMMENT ON COLUMN log.quest_reward_log.type IS 'contains: EXP, ITEM';


--
-- Name: refinelog; Type: TABLE; Schema: log; Owner: -
--

CREATE TABLE log.refinelog (
    pid bigint,
    item_name bytea,
    item_id bigint,
    step integer,
    "time" timestamp without time zone,
    is_success smallint,
    settype character varying(20) DEFAULT NULL::character varying
);


--
-- Name: COLUMN refinelog.settype; Type: COMMENT; Schema: log; Owner: -
--

COMMENT ON COLUMN log.refinelog.settype IS 'contains: HYUNIRON, POWER, SCROLL';


--
-- Name: shout_log; Type: TABLE; Schema: log; Owner: -
--

CREATE TABLE log.shout_log (
    "when" timestamp without time zone,
    "where" integer,
    empire integer,
    message bytea
);


--
-- Name: speed_hack; Type: TABLE; Schema: log; Owner: -
--

CREATE TABLE log.speed_hack (
    pid bigint,
    "time" timestamp without time zone,
    x integer,
    y integer,
    hack_count integer
);


--
-- Name: vcard_log; Type: TABLE; Schema: log; Owner: -
--

CREATE TABLE log.vcard_log (
    vcard_id bigint,
    x bigint,
    y bigint,
    hostname bytea,
    giver_name bytea,
    giver_ip bytea,
    taker_name bytea,
    taker_ip bytea
);


--
-- Name: affect; Type: TABLE; Schema: player; Owner: -
--

CREATE TABLE player.affect (
    dwpid bigint DEFAULT 0 NOT NULL,
    btype integer DEFAULT 0 NOT NULL,
    bapplyon smallint DEFAULT 0 NOT NULL,
    lapplyvalue integer DEFAULT 0 NOT NULL,
    dwflag bigint DEFAULT 0 NOT NULL,
    lduration integer DEFAULT 0 NOT NULL,
    lspcost integer DEFAULT 0 NOT NULL
);


--
-- Name: banword; Type: TABLE; Schema: player; Owner: -
--

CREATE TABLE player.banword (
    word character varying(24) DEFAULT ''::character varying NOT NULL
);


--
-- Name: dragon_soul; Type: TABLE; Schema: player; Owner: -
--

CREATE TABLE player.dragon_soul (
    id bigint NOT NULL,
    player_id bigint NOT NULL,
    refine_type smallint NOT NULL,
    applied_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: dragon_soul_id_seq; Type: SEQUENCE; Schema: player; Owner: -
--

ALTER TABLE player.dragon_soul ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME player.dragon_soul_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: guild; Type: TABLE; Schema: player; Owner: -
--

CREATE TABLE player.guild (
    id bigint NOT NULL,
    name character varying(12) DEFAULT ''::character varying NOT NULL,
    sp smallint DEFAULT 1000 NOT NULL,
    master bigint DEFAULT 0 NOT NULL,
    level smallint,
    exp integer,
    skill_point smallint DEFAULT 0 NOT NULL,
    skill bytea,
    win integer DEFAULT 0 NOT NULL,
    draw integer DEFAULT 0 NOT NULL,
    loss integer DEFAULT 0 NOT NULL,
    ladder_point integer DEFAULT 0 NOT NULL,
    gold integer DEFAULT 0 NOT NULL,
    token numeric(20,0) DEFAULT 0 NOT NULL,
    CONSTRAINT guild_gold_check CHECK ((gold >= 0))
);


--
-- Name: COLUMN guild.name; Type: COMMENT; Schema: player; Owner: -
--

COMMENT ON COLUMN player.guild.name IS 'snprintf(12u)';


--
-- Name: guild_comment; Type: TABLE; Schema: player; Owner: -
--

CREATE TABLE player.guild_comment (
    id bigint NOT NULL,
    guild_id bigint,
    name character varying(24) DEFAULT NULL::character varying,
    notice smallint,
    content character varying(50) DEFAULT NULL::character varying,
    "time" timestamp without time zone
);


--
-- Name: guild_comment_id_seq; Type: SEQUENCE; Schema: player; Owner: -
--

ALTER TABLE player.guild_comment ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME player.guild_comment_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: guild_grade; Type: TABLE; Schema: player; Owner: -
--

CREATE TABLE player.guild_grade (
    guild_id bigint DEFAULT 0 NOT NULL,
    grade smallint DEFAULT 0 NOT NULL,
    name character varying(12) DEFAULT ''::character varying NOT NULL,
    auth text,
    CONSTRAINT guild_grade_auth_check CHECK (((auth IS NULL) OR (auth = ''::text) OR (auth ~ '^(ADD_MEMBER|REMOVE_MEMEBER|NOTICE|USE_SKILL)(,(ADD_MEMBER|REMOVE_MEMEBER|NOTICE|USE_SKILL))*$'::text)))
);


--
-- Name: guild_id_seq; Type: SEQUENCE; Schema: player; Owner: -
--

ALTER TABLE player.guild ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME player.guild_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: guild_member; Type: TABLE; Schema: player; Owner: -
--

CREATE TABLE player.guild_member (
    pid bigint DEFAULT 0 NOT NULL,
    guild_id bigint DEFAULT 0 NOT NULL,
    grade smallint,
    is_general smallint DEFAULT 0 NOT NULL,
    offer bigint
);


--
-- Name: guild_war_reservation; Type: TABLE; Schema: player; Owner: -
--

CREATE TABLE player.guild_war_reservation (
    id bigint NOT NULL,
    guild1 bigint DEFAULT 0 NOT NULL,
    guild2 bigint DEFAULT 0 NOT NULL,
    "time" timestamp without time zone DEFAULT now() NOT NULL,
    type smallint DEFAULT 0 NOT NULL,
    warprice bigint DEFAULT 0 NOT NULL,
    initscore bigint DEFAULT 0 NOT NULL,
    started smallint DEFAULT 0 NOT NULL,
    bet_from bigint DEFAULT 0 NOT NULL,
    bet_to bigint DEFAULT 0 NOT NULL,
    winner integer DEFAULT '-1'::integer NOT NULL,
    power1 integer DEFAULT 0 NOT NULL,
    power2 integer DEFAULT 0 NOT NULL,
    handicap integer DEFAULT 0 NOT NULL,
    result1 integer DEFAULT 0 NOT NULL,
    result2 integer DEFAULT 0 NOT NULL
);


--
-- Name: guild_war_reservation_id_seq; Type: SEQUENCE; Schema: player; Owner: -
--

ALTER TABLE player.guild_war_reservation ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME player.guild_war_reservation_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: item; Type: TABLE; Schema: player; Owner: -
--

CREATE TABLE player.item (
    id bigint NOT NULL,
    owner_id bigint DEFAULT 0 NOT NULL,
    "window" text DEFAULT 'INVENTORY'::text NOT NULL,
    pos integer DEFAULT 0 NOT NULL,
    count bigint DEFAULT 0 NOT NULL,
    vnum bigint DEFAULT 0 NOT NULL,
    socket0 bigint DEFAULT 0 NOT NULL,
    socket1 bigint DEFAULT 0 NOT NULL,
    socket2 bigint DEFAULT 0 NOT NULL,
    attrtype0 smallint DEFAULT 0 NOT NULL,
    attrvalue0 smallint DEFAULT 0 NOT NULL,
    attrtype1 smallint DEFAULT 0 NOT NULL,
    attrvalue1 smallint DEFAULT 0 NOT NULL,
    attrtype2 smallint DEFAULT 0 NOT NULL,
    attrvalue2 smallint DEFAULT 0 NOT NULL,
    attrtype3 smallint DEFAULT 0 NOT NULL,
    attrvalue3 smallint DEFAULT 0 NOT NULL,
    attrtype4 smallint DEFAULT 0 NOT NULL,
    attrvalue4 smallint DEFAULT 0 NOT NULL,
    attrtype5 smallint DEFAULT 0 NOT NULL,
    attrvalue5 smallint DEFAULT 0 NOT NULL,
    attrtype6 smallint DEFAULT 0 NOT NULL,
    attrvalue6 smallint DEFAULT 0 NOT NULL,
    CONSTRAINT item_window_check CHECK (("window" = ANY (ARRAY['INVENTORY'::text, 'EQUIPMENT'::text, 'SAFEBOX'::text, 'MALL'::text, 'DRAGON_SOUL_INVENTORY'::text, 'BELT_INVENTORY'::text, 'GROUND'::text])))
);


--
-- Name: item_attr; Type: TABLE; Schema: player; Owner: -
--

CREATE TABLE player.item_attr (
    apply text DEFAULT 'MAX_HP'::text NOT NULL,
    prob bigint DEFAULT 0 NOT NULL,
    lv1 bigint DEFAULT 0 NOT NULL,
    lv2 bigint DEFAULT 0 NOT NULL,
    lv3 bigint DEFAULT 0 NOT NULL,
    lv4 bigint DEFAULT 0 NOT NULL,
    lv5 bigint DEFAULT 0 NOT NULL,
    weapon bigint DEFAULT 0 NOT NULL,
    body bigint DEFAULT 0 NOT NULL,
    wrist bigint DEFAULT 0 NOT NULL,
    foots bigint DEFAULT 0 NOT NULL,
    neck bigint DEFAULT 0 NOT NULL,
    head bigint DEFAULT 0 NOT NULL,
    shield bigint DEFAULT 0 NOT NULL,
    ear bigint DEFAULT 0 NOT NULL,
    costume_body bigint DEFAULT 0 NOT NULL,
    costume_hair bigint DEFAULT 0 NOT NULL,
    costume_weapon bigint DEFAULT 0 NOT NULL,
    pendant bigint DEFAULT 0 NOT NULL,
    glove bigint DEFAULT 0 NOT NULL,
    CONSTRAINT item_attr_apply_check CHECK ((apply = ANY (ARRAY['MAX_HP'::text, 'MAX_SP'::text, 'CON'::text, 'INT'::text, 'STR'::text, 'DEX'::text, 'ATT_SPEED'::text, 'MOV_SPEED'::text, 'CAST_SPEED'::text, 'HP_REGEN'::text, 'SP_REGEN'::text, 'POISON_PCT'::text, 'STUN_PCT'::text, 'SLOW_PCT'::text, 'CRITICAL_PCT'::text, 'PENETRATE_PCT'::text, 'ATTBONUS_HUMAN'::text, 'ATTBONUS_ANIMAL'::text, 'ATTBONUS_ORC'::text, 'ATTBONUS_MILGYO'::text, 'ATTBONUS_UNDEAD'::text, 'ATTBONUS_DEVIL'::text, 'STEAL_HP'::text, 'STEAL_SP'::text, 'MANA_BURN_PCT'::text, 'DAMAGE_SP_RECOVER'::text, 'BLOCK'::text, 'DODGE'::text, 'RESIST_SWORD'::text, 'RESIST_TWOHAND'::text, 'RESIST_DAGGER'::text, 'RESIST_BELL'::text, 'RESIST_FAN'::text, 'RESIST_BOW'::text, 'RESIST_FIRE'::text, 'RESIST_ELEC'::text, 'RESIST_MAGIC'::text, 'RESIST_WIND'::text, 'REFLECT_MELEE'::text, 'REFLECT_CURSE'::text, 'POISON_REDUCE'::text, 'KILL_SP_RECOVER'::text, 'EXP_DOUBLE_BONUS'::text, 'GOLD_DOUBLE_BONUS'::text, 'ITEM_DROP_BONUS'::text, 'POTION_BONUS'::text, 'KILL_HP_RECOVER'::text, 'IMMUNE_STUN'::text, 'IMMUNE_SLOW'::text, 'IMMUNE_FALL'::text, 'SKILL'::text, 'BOW_DISTANCE'::text, 'ATT_GRADE_BONUS'::text, 'DEF_GRADE_BONUS'::text, 'MAGIC_ATT_GRADE_BONUS'::text, 'MAGIC_DEF_GRADE_BONUS'::text, 'CURSE_PCT'::text, 'MAX_STAMINA'::text, 'ATT_BONUS_TO_WARRIOR'::text, 'ATT_BONUS_TO_ASSASSIN'::text, 'ATT_BONUS_TO_SURA'::text, 'ATT_BONUS_TO_SHAMAN'::text, 'ATT_BONUS_TO_MONSTER'::text, 'ATT_BONUS'::text, 'MALL_DEFBONUS'::text, 'MALL_EXPBONUS'::text, 'MALL_ITEMBONUS'::text, 'MALL_GOLDBONUS'::text, 'MAX_HP_PCT'::text, 'MAX_SP_PCT'::text, 'SKILL_DAMAGE_BONUS'::text, 'NORMAL_HIT_DAMAGE_BONUS'::text, 'SKILL_DEFEND_BONUS'::text, 'NORMAL_HIT_DEFEND_BONUS'::text, 'PC_BANG_EXP_BONUS'::text, 'PC_BANG_DROP_BONUS'::text, 'EXTRACT_HP_PCT'::text, 'RESIST_WARRIOR'::text, 'RESIST_ASSASSIN'::text, 'RESIST_SURA'::text, 'RESIST_SHAMAN'::text, 'ENERGY'::text, 'DEF_GRADE'::text, 'COSTUME_ATTR_BONUS'::text, 'MAGIC_ATT_BONUS_PER'::text, 'MELEE_MAGIC_ATT_BONUS_PER'::text, 'RESIST_ICE'::text, 'RESIST_EARTH'::text, 'RESIST_DARK'::text, 'RESIST_CRITICAL'::text, 'RESIST_PENETRATE'::text, 'BLEEDING_REDUCE'::text, 'BLEEDING_PCT'::text, 'ATT_BONUS_TO_WOLFMAN'::text, 'RESIST_WOLFMAN'::text, 'RESIST_CLAW'::text, 'ACCEDRAIN_RATE'::text, 'RESIST_MAGIC_REDUCTION'::text, 'ENCHANT_ELECT'::text, 'ENCHANT_FIRE'::text, 'ENCHANT_ICE'::text, 'ENCHANT_WIND'::text, 'ENCHANT_EARTH'::text, 'ENCHANT_DARK'::text, 'ATTBONUS_CZ'::text, 'ATTBONUS_INSECT'::text, 'ATTBONUS_DESERT'::text, 'ATTBONUS_SWORD'::text, 'ATTBONUS_TWOHAND'::text, 'ATTBONUS_DAGGER'::text, 'ATTBONUS_BELL'::text, 'ATTBONUS_FAN'::text, 'ATTBONUS_BOW'::text, 'ATTBONUS_CLAW'::text, 'RESIST_HUMAN'::text, 'RESIST_MOUNT_FALL'::text, 'UNK_117'::text, 'MOUNT'::text])))
);


--
-- Name: item_attr_rare; Type: TABLE; Schema: player; Owner: -
--

CREATE TABLE player.item_attr_rare (
    apply text DEFAULT 'MAX_HP'::text NOT NULL,
    prob bigint DEFAULT 0 NOT NULL,
    lv1 bigint DEFAULT 0 NOT NULL,
    lv2 bigint DEFAULT 0 NOT NULL,
    lv3 bigint DEFAULT 0 NOT NULL,
    lv4 bigint DEFAULT 0 NOT NULL,
    lv5 bigint DEFAULT 0 NOT NULL,
    weapon bigint DEFAULT 0 NOT NULL,
    body bigint DEFAULT 0 NOT NULL,
    wrist bigint DEFAULT 0 NOT NULL,
    foots bigint DEFAULT 0 NOT NULL,
    neck bigint DEFAULT 0 NOT NULL,
    head bigint DEFAULT 0 NOT NULL,
    shield bigint DEFAULT 0 NOT NULL,
    ear bigint DEFAULT 0 NOT NULL,
    costume_body bigint DEFAULT 0 NOT NULL,
    costume_hair bigint DEFAULT 0 NOT NULL,
    costume_weapon bigint DEFAULT 0 NOT NULL,
    pendant bigint DEFAULT 0 NOT NULL,
    glove bigint DEFAULT 0 NOT NULL,
    CONSTRAINT item_attr_rare_apply_check CHECK ((apply = ANY (ARRAY['MAX_HP'::text, 'MAX_SP'::text, 'CON'::text, 'INT'::text, 'STR'::text, 'DEX'::text, 'ATT_SPEED'::text, 'MOV_SPEED'::text, 'CAST_SPEED'::text, 'HP_REGEN'::text, 'SP_REGEN'::text, 'POISON_PCT'::text, 'STUN_PCT'::text, 'SLOW_PCT'::text, 'CRITICAL_PCT'::text, 'PENETRATE_PCT'::text, 'ATTBONUS_HUMAN'::text, 'ATTBONUS_ANIMAL'::text, 'ATTBONUS_ORC'::text, 'ATTBONUS_MILGYO'::text, 'ATTBONUS_UNDEAD'::text, 'ATTBONUS_DEVIL'::text, 'STEAL_HP'::text, 'STEAL_SP'::text, 'MANA_BURN_PCT'::text, 'DAMAGE_SP_RECOVER'::text, 'BLOCK'::text, 'DODGE'::text, 'RESIST_SWORD'::text, 'RESIST_TWOHAND'::text, 'RESIST_DAGGER'::text, 'RESIST_BELL'::text, 'RESIST_FAN'::text, 'RESIST_BOW'::text, 'RESIST_FIRE'::text, 'RESIST_ELEC'::text, 'RESIST_MAGIC'::text, 'RESIST_WIND'::text, 'REFLECT_MELEE'::text, 'REFLECT_CURSE'::text, 'POISON_REDUCE'::text, 'KILL_SP_RECOVER'::text, 'EXP_DOUBLE_BONUS'::text, 'GOLD_DOUBLE_BONUS'::text, 'ITEM_DROP_BONUS'::text, 'POTION_BONUS'::text, 'KILL_HP_RECOVER'::text, 'IMMUNE_STUN'::text, 'IMMUNE_SLOW'::text, 'IMMUNE_FALL'::text, 'SKILL'::text, 'BOW_DISTANCE'::text, 'ATT_GRADE_BONUS'::text, 'DEF_GRADE_BONUS'::text, 'MAGIC_ATT_GRADE_BONUS'::text, 'MAGIC_DEF_GRADE_BONUS'::text, 'CURSE_PCT'::text, 'MAX_STAMINA'::text, 'ATT_BONUS_TO_WARRIOR'::text, 'ATT_BONUS_TO_ASSASSIN'::text, 'ATT_BONUS_TO_SURA'::text, 'ATT_BONUS_TO_SHAMAN'::text, 'ATT_BONUS_TO_MONSTER'::text, 'ATT_BONUS'::text, 'MALL_DEFBONUS'::text, 'MALL_EXPBONUS'::text, 'MALL_ITEMBONUS'::text, 'MALL_GOLDBONUS'::text, 'MAX_HP_PCT'::text, 'MAX_SP_PCT'::text, 'SKILL_DAMAGE_BONUS'::text, 'NORMAL_HIT_DAMAGE_BONUS'::text, 'SKILL_DEFEND_BONUS'::text, 'NORMAL_HIT_DEFEND_BONUS'::text, 'PC_BANG_EXP_BONUS'::text, 'PC_BANG_DROP_BONUS'::text, 'EXTRACT_HP_PCT'::text, 'RESIST_WARRIOR'::text, 'RESIST_ASSASSIN'::text, 'RESIST_SURA'::text, 'RESIST_SHAMAN'::text, 'ENERGY'::text, 'DEF_GRADE'::text, 'COSTUME_ATTR_BONUS'::text, 'MAGIC_ATT_BONUS_PER'::text, 'MELEE_MAGIC_ATT_BONUS_PER'::text, 'RESIST_ICE'::text, 'RESIST_EARTH'::text, 'RESIST_DARK'::text, 'RESIST_CRITICAL'::text, 'RESIST_PENETRATE'::text, 'BLEEDING_REDUCE'::text, 'BLEEDING_PCT'::text, 'ATT_BONUS_TO_WOLFMAN'::text, 'RESIST_WOLFMAN'::text, 'RESIST_CLAW'::text, 'ACCEDRAIN_RATE'::text, 'RESIST_MAGIC_REDUCTION'::text, 'ENCHANT_ELECT'::text, 'ENCHANT_FIRE'::text, 'ENCHANT_ICE'::text, 'ENCHANT_WIND'::text, 'ENCHANT_EARTH'::text, 'ENCHANT_DARK'::text, 'ATTBONUS_CZ'::text, 'ATTBONUS_INSECT'::text, 'ATTBONUS_DESERT'::text, 'ATTBONUS_SWORD'::text, 'ATTBONUS_TWOHAND'::text, 'ATTBONUS_DAGGER'::text, 'ATTBONUS_BELL'::text, 'ATTBONUS_FAN'::text, 'ATTBONUS_BOW'::text, 'ATTBONUS_CLAW'::text, 'RESIST_HUMAN'::text, 'RESIST_MOUNT_FALL'::text, 'UNK_117'::text, 'MOUNT'::text])))
);


--
-- Name: item_award; Type: TABLE; Schema: player; Owner: -
--

CREATE TABLE player.item_award (
    id bigint NOT NULL,
    login character varying(16) DEFAULT ''::character varying NOT NULL,
    vnum bigint DEFAULT 0 NOT NULL,
    count bigint DEFAULT 1 NOT NULL,
    given_time timestamp without time zone DEFAULT now() NOT NULL,
    taken_time timestamp without time zone,
    item_id bigint,
    why character varying(128) DEFAULT NULL::character varying,
    socket0 bigint DEFAULT 0 NOT NULL,
    socket1 bigint DEFAULT 0 NOT NULL,
    socket2 bigint DEFAULT 0 NOT NULL,
    attrtype0 smallint DEFAULT 0 NOT NULL,
    attrvalue0 smallint DEFAULT 0 NOT NULL,
    attrtype1 smallint DEFAULT 0 NOT NULL,
    attrvalue1 smallint DEFAULT 0 NOT NULL,
    attrtype2 smallint DEFAULT 0 NOT NULL,
    attrvalue2 smallint DEFAULT 0 NOT NULL,
    attrtype3 smallint DEFAULT 0 NOT NULL,
    attrvalue3 smallint DEFAULT 0 NOT NULL,
    attrtype4 smallint DEFAULT 0 NOT NULL,
    attrvalue4 smallint DEFAULT 0 NOT NULL,
    attrtype5 smallint DEFAULT 0 NOT NULL,
    attrvalue5 smallint DEFAULT 0 NOT NULL,
    attrtype6 smallint DEFAULT 0 NOT NULL,
    attrvalue6 smallint DEFAULT 0 NOT NULL,
    mall smallint DEFAULT 1 NOT NULL
);


--
-- Name: COLUMN item_award.login; Type: COMMENT; Schema: player; Owner: -
--

COMMENT ON COLUMN player.item_award.login IS 'LOGIN_MAX_LEN=30';


--
-- Name: item_award_id_seq; Type: SEQUENCE; Schema: player; Owner: -
--

ALTER TABLE player.item_award ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME player.item_award_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: item_id_seq; Type: SEQUENCE; Schema: player; Owner: -
--

ALTER TABLE player.item ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME player.item_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: item_proto; Type: TABLE; Schema: player; Owner: -
--

CREATE TABLE player.item_proto (
    vnum bigint DEFAULT 0 NOT NULL,
    name bytea DEFAULT '\x4e6f6e616d65'::bytea NOT NULL,
    locale_name bytea DEFAULT '\x4e6f6e616d65'::bytea NOT NULL,
    type smallint DEFAULT 0 NOT NULL,
    subtype smallint DEFAULT 0 NOT NULL,
    weight smallint DEFAULT 0,
    size smallint DEFAULT 0,
    antiflag bigint DEFAULT 0,
    flag bigint DEFAULT 0,
    wearflag bigint DEFAULT 0,
    immuneflag text DEFAULT ''::text NOT NULL,
    gold integer DEFAULT 0,
    shop_buy_price bigint DEFAULT 0 NOT NULL,
    refined_vnum bigint DEFAULT 0 NOT NULL,
    refine_set integer DEFAULT 0 NOT NULL,
    refine_set2 integer DEFAULT 0 NOT NULL,
    magic_pct smallint DEFAULT 0 NOT NULL,
    limittype0 smallint DEFAULT 0,
    limitvalue0 integer DEFAULT 0,
    limittype1 smallint DEFAULT 0,
    limitvalue1 integer DEFAULT 0,
    applytype0 smallint DEFAULT 0,
    applyvalue0 integer DEFAULT 0,
    applytype1 smallint DEFAULT 0,
    applyvalue1 integer DEFAULT 0,
    applytype2 smallint DEFAULT 0,
    applyvalue2 integer DEFAULT 0,
    value0 integer DEFAULT 0,
    value1 integer DEFAULT 0,
    value2 integer DEFAULT 0,
    value3 integer DEFAULT 0,
    value4 integer DEFAULT 0,
    value5 integer DEFAULT 0,
    socket0 smallint DEFAULT '-1'::integer,
    socket1 smallint DEFAULT '-1'::integer,
    socket2 smallint DEFAULT '-1'::integer,
    socket3 smallint DEFAULT '-1'::integer,
    socket4 smallint DEFAULT '-1'::integer,
    socket5 smallint DEFAULT '-1'::integer,
    specular smallint DEFAULT 0 NOT NULL,
    socket_pct smallint DEFAULT 0 NOT NULL,
    addon_type smallint DEFAULT 0 NOT NULL
);


--
-- Name: land; Type: TABLE; Schema: player; Owner: -
--

CREATE TABLE player.land (
    id bigint NOT NULL,
    map_index bigint DEFAULT 0 NOT NULL,
    x bigint DEFAULT 0 NOT NULL,
    y bigint DEFAULT 0 NOT NULL,
    width bigint DEFAULT 0 NOT NULL,
    height bigint DEFAULT 0 NOT NULL,
    guild_id bigint DEFAULT 0 NOT NULL,
    guild_level_limit smallint DEFAULT 0 NOT NULL,
    price bigint DEFAULT 0 NOT NULL,
    enable text DEFAULT 'NO'::text NOT NULL,
    CONSTRAINT land_enable_check CHECK ((enable = ANY (ARRAY['YES'::text, 'NO'::text])))
);


--
-- Name: land_id_seq; Type: SEQUENCE; Schema: player; Owner: -
--

ALTER TABLE player.land ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME player.land_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: marriage; Type: TABLE; Schema: player; Owner: -
--

CREATE TABLE player.marriage (
    is_married smallint DEFAULT 0 NOT NULL,
    pid1 bigint DEFAULT 0 NOT NULL,
    pid2 bigint DEFAULT 0 NOT NULL,
    love_point bigint,
    "time" bigint DEFAULT 0 NOT NULL
);


--
-- Name: messenger_list; Type: TABLE; Schema: player; Owner: -
--

CREATE TABLE player.messenger_list (
    account character varying(16) DEFAULT ''::character varying NOT NULL,
    companion character varying(16) DEFAULT ''::character varying NOT NULL
);


--
-- Name: COLUMN messenger_list.account; Type: COMMENT; Schema: player; Owner: -
--

COMMENT ON COLUMN player.messenger_list.account IS '24 at maximum';


--
-- Name: COLUMN messenger_list.companion; Type: COMMENT; Schema: player; Owner: -
--

COMMENT ON COLUMN player.messenger_list.companion IS '24 at maximum';


--
-- Name: mob_proto; Type: TABLE; Schema: player; Owner: -
--

CREATE TABLE player.mob_proto (
    vnum bigint DEFAULT 0 NOT NULL,
    name character varying(24) DEFAULT 'Noname'::character varying NOT NULL,
    locale_name bytea DEFAULT '\x4e6f6e616d65'::bytea NOT NULL,
    rank smallint DEFAULT 0 NOT NULL,
    type smallint DEFAULT 0 NOT NULL,
    battle_type smallint DEFAULT 0 NOT NULL,
    level integer DEFAULT 1 NOT NULL,
    size text DEFAULT 'SMALL'::text NOT NULL,
    ai_flag text,
    mount_capacity smallint DEFAULT 0 NOT NULL,
    setraceflag text DEFAULT ''::text NOT NULL,
    setimmuneflag text DEFAULT ''::text NOT NULL,
    empire smallint DEFAULT 0 NOT NULL,
    folder character varying(100) DEFAULT ''::character varying NOT NULL,
    on_click smallint DEFAULT 0 NOT NULL,
    st integer DEFAULT 0 NOT NULL,
    dx integer DEFAULT 0 NOT NULL,
    ht integer DEFAULT 0 NOT NULL,
    iq integer DEFAULT 0 NOT NULL,
    damage_min integer DEFAULT 0 NOT NULL,
    damage_max integer DEFAULT 0 NOT NULL,
    max_hp bigint DEFAULT 0 NOT NULL,
    regen_cycle smallint DEFAULT 0 NOT NULL,
    regen_percent smallint DEFAULT 0 NOT NULL,
    gold_min integer DEFAULT 0 NOT NULL,
    gold_max integer DEFAULT 0 NOT NULL,
    exp bigint DEFAULT 0 NOT NULL,
    def integer DEFAULT 0 NOT NULL,
    attack_speed integer DEFAULT 100 NOT NULL,
    move_speed integer DEFAULT 100 NOT NULL,
    aggressive_hp_pct smallint DEFAULT 0 NOT NULL,
    aggressive_sight integer DEFAULT 0 NOT NULL,
    attack_range integer DEFAULT 0 NOT NULL,
    drop_item bigint DEFAULT 0 NOT NULL,
    resurrection_vnum bigint DEFAULT 0 NOT NULL,
    enchant_curse smallint DEFAULT 0 NOT NULL,
    enchant_slow smallint DEFAULT 0 NOT NULL,
    enchant_poison smallint DEFAULT 0 NOT NULL,
    enchant_stun smallint DEFAULT 0 NOT NULL,
    enchant_critical smallint DEFAULT 0 NOT NULL,
    enchant_penetrate smallint DEFAULT 0 NOT NULL,
    resist_sword smallint DEFAULT 0 NOT NULL,
    resist_twohand smallint DEFAULT 0 NOT NULL,
    resist_dagger smallint DEFAULT 0 NOT NULL,
    resist_bell smallint DEFAULT 0 NOT NULL,
    resist_fan smallint DEFAULT 0 NOT NULL,
    resist_bow smallint DEFAULT 0 NOT NULL,
    resist_fire smallint DEFAULT 0 NOT NULL,
    resist_elect smallint DEFAULT 0 NOT NULL,
    resist_magic smallint DEFAULT 0 NOT NULL,
    resist_wind smallint DEFAULT 0 NOT NULL,
    resist_poison smallint DEFAULT 0 NOT NULL,
    dam_multiply real,
    summon integer,
    drain_sp integer,
    mob_color bigint,
    polymorph_item bigint DEFAULT 0 NOT NULL,
    skill_level0 smallint,
    skill_vnum0 bigint,
    skill_level1 smallint,
    skill_vnum1 bigint,
    skill_level2 smallint,
    skill_vnum2 bigint,
    skill_level3 smallint,
    skill_vnum3 bigint,
    skill_level4 smallint,
    skill_vnum4 bigint,
    sp_berserk smallint DEFAULT 0 NOT NULL,
    sp_stoneskin smallint DEFAULT 0 NOT NULL,
    sp_godspeed smallint DEFAULT 0 NOT NULL,
    sp_deathblow smallint DEFAULT 0 NOT NULL,
    sp_revive smallint DEFAULT 0 NOT NULL
);


--
-- Name: monarch; Type: TABLE; Schema: player; Owner: -
--

CREATE TABLE player.monarch (
    empire bigint DEFAULT 0 NOT NULL,
    pid bigint,
    windate timestamp without time zone,
    money numeric(20,0) DEFAULT NULL::numeric
);


--
-- Name: object; Type: TABLE; Schema: player; Owner: -
--

CREATE TABLE player.object (
    id bigint NOT NULL,
    land_id bigint DEFAULT 0 NOT NULL,
    vnum bigint DEFAULT 0 NOT NULL,
    map_index bigint DEFAULT 0 NOT NULL,
    x integer DEFAULT 0 NOT NULL,
    y integer DEFAULT 0 NOT NULL,
    x_rot real DEFAULT 0 NOT NULL,
    y_rot real DEFAULT 0 NOT NULL,
    z_rot real DEFAULT 0 NOT NULL,
    life integer DEFAULT 0 NOT NULL
);


--
-- Name: object_id_seq; Type: SEQUENCE; Schema: player; Owner: -
--

ALTER TABLE player.object ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME player.object_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: object_proto; Type: TABLE; Schema: player; Owner: -
--

CREATE TABLE player.object_proto (
    vnum bigint DEFAULT 0 NOT NULL,
    name character varying(32) DEFAULT ''::character varying NOT NULL,
    price bigint DEFAULT 0 NOT NULL,
    materials character varying(64) DEFAULT ''::character varying NOT NULL,
    upgrade_vnum bigint DEFAULT 0 NOT NULL,
    upgrade_limit_time bigint DEFAULT 0 NOT NULL,
    life integer DEFAULT 0 NOT NULL,
    reg_1 integer DEFAULT 0 NOT NULL,
    reg_2 integer DEFAULT 0 NOT NULL,
    reg_3 integer DEFAULT 0 NOT NULL,
    reg_4 integer DEFAULT 0 NOT NULL,
    npc bigint DEFAULT 0 NOT NULL,
    group_vnum bigint DEFAULT 0 NOT NULL,
    dependent_group bigint DEFAULT 0 NOT NULL
);


--
-- Name: player; Type: TABLE; Schema: player; Owner: -
--

CREATE TABLE player.player (
    id bigint NOT NULL,
    account_id bigint DEFAULT 0 NOT NULL,
    name character varying(24) DEFAULT 'NONAME'::character varying NOT NULL,
    job smallint DEFAULT 0 NOT NULL,
    voice smallint DEFAULT 0 NOT NULL,
    dir smallint DEFAULT 0 NOT NULL,
    x integer DEFAULT 0 NOT NULL,
    y integer DEFAULT 0 NOT NULL,
    z integer DEFAULT 0 NOT NULL,
    map_index integer DEFAULT 0 NOT NULL,
    exit_x integer DEFAULT 0 NOT NULL,
    exit_y integer DEFAULT 0 NOT NULL,
    exit_map_index integer DEFAULT 0 NOT NULL,
    hp integer DEFAULT 0 NOT NULL,
    mp integer DEFAULT 0 NOT NULL,
    stamina smallint DEFAULT 0 NOT NULL,
    random_hp smallint DEFAULT 0 NOT NULL,
    random_sp smallint DEFAULT 0 NOT NULL,
    playtime integer DEFAULT 0 NOT NULL,
    level smallint DEFAULT 1 NOT NULL,
    level_step smallint DEFAULT 0 NOT NULL,
    st smallint DEFAULT 0 NOT NULL,
    ht smallint DEFAULT 0 NOT NULL,
    dx smallint DEFAULT 0 NOT NULL,
    iq smallint DEFAULT 0 NOT NULL,
    exp integer DEFAULT 0 NOT NULL,
    gold integer DEFAULT 0 NOT NULL,
    cheque integer DEFAULT 0 NOT NULL,
    stat_point smallint DEFAULT 0 NOT NULL,
    skill_point smallint DEFAULT 0 NOT NULL,
    quickslot bytea,
    ip character varying(15) DEFAULT '0.0.0.0'::character varying,
    part_main bigint DEFAULT 0 NOT NULL,
    part_base smallint DEFAULT 0 NOT NULL,
    part_hair bigint DEFAULT 0 NOT NULL,
    part_acce bigint DEFAULT 0 NOT NULL,
    skill_group smallint DEFAULT 0 NOT NULL,
    skill_level bytea,
    alignment integer DEFAULT 0 NOT NULL,
    last_play timestamp without time zone DEFAULT now() NOT NULL,
    change_name smallint DEFAULT 0 NOT NULL,
    mobile character varying(24) DEFAULT NULL::character varying,
    sub_skill_point smallint DEFAULT 0 NOT NULL,
    stat_reset_count smallint DEFAULT 0 NOT NULL,
    horse_hp smallint DEFAULT 0 NOT NULL,
    horse_stamina smallint DEFAULT 0 NOT NULL,
    horse_level smallint DEFAULT 0 NOT NULL,
    horse_hp_droptime bigint DEFAULT 0 NOT NULL,
    horse_riding smallint DEFAULT 0 NOT NULL,
    horse_skill_point smallint DEFAULT 0 NOT NULL,
    CONSTRAINT player_gold_check CHECK ((gold >= 0))
);


--
-- Name: COLUMN player.random_hp; Type: COMMENT; Schema: player; Owner: -
--

COMMENT ON COLUMN player.player.random_hp IS 'if lvl 0, it will be negative';


--
-- Name: COLUMN player.random_sp; Type: COMMENT; Schema: player; Owner: -
--

COMMENT ON COLUMN player.player.random_sp IS 'if lvl 0, it will be negative';


--
-- Name: player_id_seq; Type: SEQUENCE; Schema: player; Owner: -
--

ALTER TABLE player.player ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME player.player_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: player_index; Type: TABLE; Schema: player; Owner: -
--

CREATE TABLE player.player_index (
    id bigint DEFAULT 0 NOT NULL,
    pid1 bigint DEFAULT 0 NOT NULL,
    pid2 bigint DEFAULT 0 NOT NULL,
    pid3 bigint DEFAULT 0 NOT NULL,
    pid4 bigint DEFAULT 0 NOT NULL,
    pid5 bigint DEFAULT 0 NOT NULL,
    empire smallint DEFAULT 0 NOT NULL
);


--
-- Name: quest; Type: TABLE; Schema: player; Owner: -
--

CREATE TABLE player.quest (
    dwpid bigint DEFAULT 0 NOT NULL,
    szname character varying(32) DEFAULT ''::character varying NOT NULL,
    szstate character varying(64) DEFAULT ''::character varying NOT NULL,
    lvalue integer DEFAULT 0 NOT NULL
);


--
-- Name: refine_proto; Type: TABLE; Schema: player; Owner: -
--

CREATE TABLE player.refine_proto (
    id integer NOT NULL,
    vnum0 bigint DEFAULT 0 NOT NULL,
    count0 smallint DEFAULT 0 NOT NULL,
    vnum1 bigint DEFAULT 0 NOT NULL,
    count1 smallint DEFAULT 0 NOT NULL,
    vnum2 bigint DEFAULT 0 NOT NULL,
    count2 smallint DEFAULT 0 NOT NULL,
    vnum3 bigint DEFAULT 0 NOT NULL,
    count3 smallint DEFAULT 0 NOT NULL,
    vnum4 bigint DEFAULT 0 NOT NULL,
    count4 smallint DEFAULT 0 NOT NULL,
    cost integer DEFAULT 0 NOT NULL,
    src_vnum bigint DEFAULT 0 NOT NULL,
    result_vnum bigint DEFAULT 0 NOT NULL,
    prob smallint DEFAULT 100 NOT NULL
);


--
-- Name: refine_proto_id_seq; Type: SEQUENCE; Schema: player; Owner: -
--

ALTER TABLE player.refine_proto ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME player.refine_proto_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: safebox; Type: TABLE; Schema: player; Owner: -
--

CREATE TABLE player.safebox (
    account_id bigint DEFAULT 0 NOT NULL,
    size smallint DEFAULT 0 NOT NULL,
    password character varying(6) DEFAULT ''::character varying NOT NULL,
    gold integer DEFAULT 0 NOT NULL,
    CONSTRAINT safebox_gold_check CHECK ((gold >= 0))
);


--
-- Name: shop; Type: TABLE; Schema: player; Owner: -
--

CREATE TABLE player.shop (
    vnum integer DEFAULT 0 NOT NULL,
    name character varying(32) DEFAULT 'Noname'::character varying NOT NULL,
    npc_vnum smallint DEFAULT 0 NOT NULL
);


--
-- Name: shop_item; Type: TABLE; Schema: player; Owner: -
--

CREATE TABLE player.shop_item (
    shop_vnum integer DEFAULT 0 NOT NULL,
    item_vnum integer DEFAULT 0 NOT NULL,
    count bigint DEFAULT 1 NOT NULL
);


--
-- Name: skill_proto; Type: TABLE; Schema: player; Owner: -
--

CREATE TABLE player.skill_proto (
    dwvnum integer DEFAULT 0 NOT NULL,
    szname bytea DEFAULT '\x'::bytea NOT NULL,
    btype smallint DEFAULT 0 NOT NULL,
    blevelstep smallint DEFAULT 0 NOT NULL,
    bmaxlevel smallint DEFAULT 0 NOT NULL,
    blevellimit smallint DEFAULT 0 NOT NULL,
    szpointon text DEFAULT 'NONE'::text NOT NULL,
    szpointpoly character varying(100) DEFAULT ''::character varying NOT NULL,
    szspcostpoly character varying(100) DEFAULT ''::character varying NOT NULL,
    szdurationpoly character varying(100) DEFAULT ''::character varying NOT NULL,
    szdurationspcostpoly character varying(100) DEFAULT ''::character varying NOT NULL,
    szcooldownpoly character varying(100) DEFAULT ''::character varying NOT NULL,
    szmasterbonuspoly character varying(100) DEFAULT ''::character varying NOT NULL,
    szattackgradepoly character varying(100) DEFAULT ''::character varying NOT NULL,
    setflag text,
    setaffectflag text DEFAULT 'YMIR'::text NOT NULL,
    szpointon2 text DEFAULT 'NONE'::text NOT NULL,
    szpointpoly2 character varying(100) DEFAULT ''::character varying NOT NULL,
    szdurationpoly2 character varying(100) DEFAULT ''::character varying NOT NULL,
    setaffectflag2 text DEFAULT 'YMIR'::text NOT NULL,
    szpointon3 character varying(100) DEFAULT 'NONE'::character varying NOT NULL,
    szpointpoly3 character varying(100) DEFAULT ''::character varying NOT NULL,
    szdurationpoly3 character varying(100) DEFAULT ''::character varying NOT NULL,
    szgrandmasteraddspcostpoly character varying(100) DEFAULT ''::character varying NOT NULL,
    prerequisiteskillvnum integer DEFAULT 0 NOT NULL,
    prerequisiteskilllevel integer DEFAULT 0 NOT NULL,
    eskilltype text DEFAULT 'NORMAL'::text NOT NULL,
    imaxhit smallint DEFAULT 0 NOT NULL,
    szsplasharounddamageadjustpoly character varying(100) DEFAULT '1'::character varying NOT NULL,
    dwtargetrange integer DEFAULT 1000 NOT NULL,
    dwsplashrange bigint DEFAULT 0 NOT NULL,
    CONSTRAINT skill_proto_eskilltype_check CHECK ((eskilltype = ANY (ARRAY['NORMAL'::text, 'MELEE'::text, 'RANGE'::text, 'MAGIC'::text]))),
    CONSTRAINT skill_proto_szpointon2_check CHECK ((szpointon2 = ANY (ARRAY['NONE'::text, 'MAX_HP'::text, 'MAX_SP'::text, 'HP_REGEN'::text, 'SP_REGEN'::text, 'BLOCK'::text, 'HP'::text, 'SP'::text, 'ATT_GRADE'::text, 'DEF_GRADE'::text, 'MAGIC_ATT_GRADE'::text, 'MAGIC_DEF_GRADE'::text, 'BOW_DISTANCE'::text, 'MOV_SPEED'::text, 'ATT_SPEED'::text, 'POISON_PCT'::text, 'RESIST_RANGE'::text, 'RESIST_MELEE'::text, 'CASTING_SPEED'::text, 'REFLECT_MELEE'::text, 'ATT_BONUS'::text, 'DEF_BONUS'::text, 'RESIST_NORMAL'::text, 'DODGE'::text, 'KILL_HP_RECOVER'::text, 'KILL_SP_RECOVER'::text, 'HIT_HP_RECOVER'::text, 'HIT_SP_RECOVER'::text, 'CRITICAL'::text, 'MANASHIELD'::text, 'SKILL_DAMAGE_BONUS'::text, 'NORMAL_HIT_DAMAGE_BONUS'::text]))),
    CONSTRAINT skill_proto_szpointon_check CHECK ((szpointon = ANY (ARRAY['NONE'::text, 'MAX_HP'::text, 'MAX_SP'::text, 'HP_REGEN'::text, 'SP_REGEN'::text, 'BLOCK'::text, 'HP'::text, 'SP'::text, 'ATT_GRADE'::text, 'DEF_GRADE'::text, 'MAGIC_ATT_GRADE'::text, 'MAGIC_DEF_GRADE'::text, 'BOW_DISTANCE'::text, 'MOV_SPEED'::text, 'ATT_SPEED'::text, 'POISON_PCT'::text, 'RESIST_RANGE'::text, 'RESIST_MELEE'::text, 'CASTING_SPEED'::text, 'REFLECT_MELEE'::text, 'ATT_BONUS'::text, 'DEF_BONUS'::text, 'RESIST_NORMAL'::text, 'DODGE'::text, 'KILL_HP_RECOVER'::text, 'KILL_SP_RECOVER'::text, 'HIT_HP_RECOVER'::text, 'HIT_SP_RECOVER'::text, 'CRITICAL'::text, 'MANASHIELD'::text, 'SKILL_DAMAGE_BONUS'::text, 'NORMAL_HIT_DAMAGE_BONUS'::text])))
);


--
-- Name: maps; Type: TABLE; Schema: world; Owner: -
--

CREATE TABLE world.maps (
    map_id integer NOT NULL,
    name text NOT NULL,
    base_x integer NOT NULL,
    base_y integer NOT NULL,
    spawn_x integer NOT NULL,
    spawn_y integer NOT NULL
);


--
-- Name: spawns; Type: TABLE; Schema: world; Owner: -
--

CREATE TABLE world.spawns (
    map_id integer NOT NULL,
    vnum bigint NOT NULL,
    x integer NOT NULL,
    y integer NOT NULL,
    count integer NOT NULL,
    kind text NOT NULL
);


--
-- Name: account account_login_key; Type: CONSTRAINT; Schema: account; Owner: -
--

ALTER TABLE ONLY account.account
    ADD CONSTRAINT account_login_key UNIQUE (login);


--
-- Name: account account_pkey; Type: CONSTRAINT; Schema: account; Owner: -
--

ALTER TABLE ONLY account.account
    ADD CONSTRAINT account_pkey PRIMARY KEY (id);


--
-- Name: exp_table exp_table_pkey; Type: CONSTRAINT; Schema: common; Owner: -
--

ALTER TABLE ONLY common.exp_table
    ADD CONSTRAINT exp_table_pkey PRIMARY KEY (level);


--
-- Name: gmhost gmhost_pkey; Type: CONSTRAINT; Schema: common; Owner: -
--

ALTER TABLE ONLY common.gmhost
    ADD CONSTRAINT gmhost_pkey PRIMARY KEY (mip);


--
-- Name: gmlist gmlist_pkey; Type: CONSTRAINT; Schema: common; Owner: -
--

ALTER TABLE ONLY common.gmlist
    ADD CONSTRAINT gmlist_pkey PRIMARY KEY (mid);


--
-- Name: item_descriptions item_descriptions_pkey; Type: CONSTRAINT; Schema: common; Owner: -
--

ALTER TABLE ONLY common.item_descriptions
    ADD CONSTRAINT item_descriptions_pkey PRIMARY KEY (vnum, lang);


--
-- Name: item_icons item_icons_pkey; Type: CONSTRAINT; Schema: common; Owner: -
--

ALTER TABLE ONLY common.item_icons
    ADD CONSTRAINT item_icons_pkey PRIMARY KEY (vnum);


--
-- Name: item_names item_names_pkey; Type: CONSTRAINT; Schema: common; Owner: -
--

ALTER TABLE ONLY common.item_names
    ADD CONSTRAINT item_names_pkey PRIMARY KEY (vnum, lang);


--
-- Name: locale locale_pkey; Type: CONSTRAINT; Schema: common; Owner: -
--

ALTER TABLE ONLY common.locale
    ADD CONSTRAINT locale_pkey PRIMARY KEY (mkey);


--
-- Name: map_names map_names_pkey; Type: CONSTRAINT; Schema: common; Owner: -
--

ALTER TABLE ONLY common.map_names
    ADD CONSTRAINT map_names_pkey PRIMARY KEY (map_id, lang);


--
-- Name: message_texts message_texts_pkey; Type: CONSTRAINT; Schema: common; Owner: -
--

ALTER TABLE ONLY common.message_texts
    ADD CONSTRAINT message_texts_pkey PRIMARY KEY (key, lang);


--
-- Name: mob_names mob_names_pkey; Type: CONSTRAINT; Schema: common; Owner: -
--

ALTER TABLE ONLY common.mob_names
    ADD CONSTRAINT mob_names_pkey PRIMARY KEY (vnum, lang);


--
-- Name: priv_settings priv_settings_pkey; Type: CONSTRAINT; Schema: common; Owner: -
--

ALTER TABLE ONLY common.priv_settings
    ADD CONSTRAINT priv_settings_pkey PRIMARY KEY (priv_type, id, type);


--
-- Name: skill_names skill_names_pkey; Type: CONSTRAINT; Schema: common; Owner: -
--

ALTER TABLE ONLY common.skill_names
    ADD CONSTRAINT skill_names_pkey PRIMARY KEY (skill_id, lang);


--
-- Name: spam_db spam_db_pkey; Type: CONSTRAINT; Schema: common; Owner: -
--

ALTER TABLE ONLY common.spam_db
    ADD CONSTRAINT spam_db_pkey PRIMARY KEY (word);


--
-- Name: ui_texts ui_texts_pkey; Type: CONSTRAINT; Schema: common; Owner: -
--

ALTER TABLE ONLY common.ui_texts
    ADD CONSTRAINT ui_texts_pkey PRIMARY KEY (key, lang);


--
-- Name: mutation_audit mutation_audit_pkey; Type: CONSTRAINT; Schema: log; Owner: -
--

ALTER TABLE ONLY log.mutation_audit
    ADD CONSTRAINT mutation_audit_pkey PRIMARY KEY (mutation_id);


--
-- Name: affect affect_pkey; Type: CONSTRAINT; Schema: player; Owner: -
--

ALTER TABLE ONLY player.affect
    ADD CONSTRAINT affect_pkey PRIMARY KEY (dwpid, btype, bapplyon, lapplyvalue);


--
-- Name: banword banword_pkey; Type: CONSTRAINT; Schema: player; Owner: -
--

ALTER TABLE ONLY player.banword
    ADD CONSTRAINT banword_pkey PRIMARY KEY (word);


--
-- Name: dragon_soul dragon_soul_pkey; Type: CONSTRAINT; Schema: player; Owner: -
--

ALTER TABLE ONLY player.dragon_soul
    ADD CONSTRAINT dragon_soul_pkey PRIMARY KEY (id);


--
-- Name: guild_comment guild_comment_pkey; Type: CONSTRAINT; Schema: player; Owner: -
--

ALTER TABLE ONLY player.guild_comment
    ADD CONSTRAINT guild_comment_pkey PRIMARY KEY (id);


--
-- Name: guild_grade guild_grade_pkey; Type: CONSTRAINT; Schema: player; Owner: -
--

ALTER TABLE ONLY player.guild_grade
    ADD CONSTRAINT guild_grade_pkey PRIMARY KEY (guild_id, grade);


--
-- Name: guild_member guild_member_pkey; Type: CONSTRAINT; Schema: player; Owner: -
--

ALTER TABLE ONLY player.guild_member
    ADD CONSTRAINT guild_member_pkey PRIMARY KEY (guild_id, pid);


--
-- Name: guild guild_pkey; Type: CONSTRAINT; Schema: player; Owner: -
--

ALTER TABLE ONLY player.guild
    ADD CONSTRAINT guild_pkey PRIMARY KEY (id);


--
-- Name: guild_war_reservation guild_war_reservation_pkey; Type: CONSTRAINT; Schema: player; Owner: -
--

ALTER TABLE ONLY player.guild_war_reservation
    ADD CONSTRAINT guild_war_reservation_pkey PRIMARY KEY (id);


--
-- Name: item_award item_award_pkey; Type: CONSTRAINT; Schema: player; Owner: -
--

ALTER TABLE ONLY player.item_award
    ADD CONSTRAINT item_award_pkey PRIMARY KEY (id);


--
-- Name: item item_pkey; Type: CONSTRAINT; Schema: player; Owner: -
--

ALTER TABLE ONLY player.item
    ADD CONSTRAINT item_pkey PRIMARY KEY (id);


--
-- Name: item_proto item_proto_pkey; Type: CONSTRAINT; Schema: player; Owner: -
--

ALTER TABLE ONLY player.item_proto
    ADD CONSTRAINT item_proto_pkey PRIMARY KEY (vnum);


--
-- Name: land land_pkey; Type: CONSTRAINT; Schema: player; Owner: -
--

ALTER TABLE ONLY player.land
    ADD CONSTRAINT land_pkey PRIMARY KEY (id);


--
-- Name: marriage marriage_pkey; Type: CONSTRAINT; Schema: player; Owner: -
--

ALTER TABLE ONLY player.marriage
    ADD CONSTRAINT marriage_pkey PRIMARY KEY (pid1, pid2);


--
-- Name: messenger_list messenger_list_pkey; Type: CONSTRAINT; Schema: player; Owner: -
--

ALTER TABLE ONLY player.messenger_list
    ADD CONSTRAINT messenger_list_pkey PRIMARY KEY (account, companion);


--
-- Name: mob_proto mob_proto_pkey; Type: CONSTRAINT; Schema: player; Owner: -
--

ALTER TABLE ONLY player.mob_proto
    ADD CONSTRAINT mob_proto_pkey PRIMARY KEY (vnum);


--
-- Name: monarch monarch_pkey; Type: CONSTRAINT; Schema: player; Owner: -
--

ALTER TABLE ONLY player.monarch
    ADD CONSTRAINT monarch_pkey PRIMARY KEY (empire);


--
-- Name: object object_pkey; Type: CONSTRAINT; Schema: player; Owner: -
--

ALTER TABLE ONLY player.object
    ADD CONSTRAINT object_pkey PRIMARY KEY (id);


--
-- Name: object_proto object_proto_pkey; Type: CONSTRAINT; Schema: player; Owner: -
--

ALTER TABLE ONLY player.object_proto
    ADD CONSTRAINT object_proto_pkey PRIMARY KEY (vnum);


--
-- Name: player_index player_index_pkey; Type: CONSTRAINT; Schema: player; Owner: -
--

ALTER TABLE ONLY player.player_index
    ADD CONSTRAINT player_index_pkey PRIMARY KEY (id);


--
-- Name: player player_pkey; Type: CONSTRAINT; Schema: player; Owner: -
--

ALTER TABLE ONLY player.player
    ADD CONSTRAINT player_pkey PRIMARY KEY (id);


--
-- Name: quest quest_pkey; Type: CONSTRAINT; Schema: player; Owner: -
--

ALTER TABLE ONLY player.quest
    ADD CONSTRAINT quest_pkey PRIMARY KEY (dwpid, szname, szstate);


--
-- Name: refine_proto refine_proto_pkey; Type: CONSTRAINT; Schema: player; Owner: -
--

ALTER TABLE ONLY player.refine_proto
    ADD CONSTRAINT refine_proto_pkey PRIMARY KEY (id);


--
-- Name: safebox safebox_pkey; Type: CONSTRAINT; Schema: player; Owner: -
--

ALTER TABLE ONLY player.safebox
    ADD CONSTRAINT safebox_pkey PRIMARY KEY (account_id);


--
-- Name: shop_item shop_item_shop_vnum_item_vnum_count_key; Type: CONSTRAINT; Schema: player; Owner: -
--

ALTER TABLE ONLY player.shop_item
    ADD CONSTRAINT shop_item_shop_vnum_item_vnum_count_key UNIQUE (shop_vnum, item_vnum, count);


--
-- Name: shop shop_pkey; Type: CONSTRAINT; Schema: player; Owner: -
--

ALTER TABLE ONLY player.shop
    ADD CONSTRAINT shop_pkey PRIMARY KEY (vnum);


--
-- Name: skill_proto skill_proto_pkey; Type: CONSTRAINT; Schema: player; Owner: -
--

ALTER TABLE ONLY player.skill_proto
    ADD CONSTRAINT skill_proto_pkey PRIMARY KEY (dwvnum);


--
-- Name: maps maps_pkey; Type: CONSTRAINT; Schema: world; Owner: -
--

ALTER TABLE ONLY world.maps
    ADD CONSTRAINT maps_pkey PRIMARY KEY (map_id);


--
-- Name: social_id; Type: INDEX; Schema: account; Owner: -
--

CREATE INDEX social_id ON account.account USING btree (social_id);


--
-- Name: account_id_idx; Type: INDEX; Schema: player; Owner: -
--

CREATE INDEX account_id_idx ON player.player USING btree (account_id);


--
-- Name: guild_comment_guild_id_idx; Type: INDEX; Schema: player; Owner: -
--

CREATE INDEX guild_comment_guild_id_idx ON player.guild_comment USING btree (guild_id);


--
-- Name: guild_member_pid_key; Type: INDEX; Schema: player; Owner: -
--

CREATE UNIQUE INDEX guild_member_pid_key ON player.guild_member USING btree (pid);


--
-- Name: item_award_given_time_idx; Type: INDEX; Schema: player; Owner: -
--

CREATE INDEX item_award_given_time_idx ON player.item_award USING btree (given_time);


--
-- Name: item_award_taken_time_idx; Type: INDEX; Schema: player; Owner: -
--

CREATE INDEX item_award_taken_time_idx ON player.item_award USING btree (taken_time);


--
-- Name: item_item_vnum_index; Type: INDEX; Schema: player; Owner: -
--

CREATE INDEX item_item_vnum_index ON player.item USING btree (vnum);


--
-- Name: item_owner_id_idx; Type: INDEX; Schema: player; Owner: -
--

CREATE INDEX item_owner_id_idx ON player.item USING btree (owner_id);


--
-- Name: name_idx; Type: INDEX; Schema: player; Owner: -
--

CREATE INDEX name_idx ON player.player USING btree (name);


--
-- Name: pid1_key; Type: INDEX; Schema: player; Owner: -
--

CREATE INDEX pid1_key ON player.player_index USING btree (pid1);


--
-- Name: pid2_key; Type: INDEX; Schema: player; Owner: -
--

CREATE INDEX pid2_key ON player.player_index USING btree (pid2);


--
-- Name: pid3_key; Type: INDEX; Schema: player; Owner: -
--

CREATE INDEX pid3_key ON player.player_index USING btree (pid3);


--
-- Name: pid4_key; Type: INDEX; Schema: player; Owner: -
--

CREATE INDEX pid4_key ON player.player_index USING btree (pid4);


--
-- Name: pid5_key; Type: INDEX; Schema: player; Owner: -
--

CREATE INDEX pid5_key ON player.player_index USING btree (pid5);


--
-- Name: quest_name_idx; Type: INDEX; Schema: player; Owner: -
--

CREATE INDEX quest_name_idx ON player.quest USING btree (szname);


--
-- Name: quest_pid_idx; Type: INDEX; Schema: player; Owner: -
--

CREATE INDEX quest_pid_idx ON player.quest USING btree (dwpid);


--
-- Name: quest_state_idx; Type: INDEX; Schema: player; Owner: -
--

CREATE INDEX quest_state_idx ON player.quest USING btree (szstate);


--
-- Name: spawns_map_idx; Type: INDEX; Schema: world; Owner: -
--

CREATE INDEX spawns_map_idx ON world.spawns USING btree (map_id);


--
-- PostgreSQL database dump complete
--

\unrestrict f7Kq3BNIAtznVq5kfhkFDrcAmKVBHZXrTSErREpXWD1CeM0gr72xdMI2bBFtjMl

