[package]
name = "server_realms"
version.workspace = true
edition.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
protocol = { path = "../protocol" }
network = { path = "../network" }
database = { path = "../database" }
game_core = { path = "../game_core" }
quest_dsl = { path = "../quest_dsl" }
tokio-postgres.workspace = true
tokio.workspace = true
