[workspace]
resolver = "3"
members = ["protocol", "network", "database", "realm", "server_realms", "mysql_proxy"]

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "MPL-2.0"

[workspace.dependencies]
tokio = { version = "1.49", features = ["rt-multi-thread", "net", "io-util", "time", "sync", "macros", "test-util"] }
tokio-postgres = { version = "0.7", features = ["with-uuid-1"] }
uuid = "1"

[workspace.lints.rust]
unsafe_code = "forbid"
