#!/usr/bin/env python3
# G-PG part 2/3: generate PostgreSQL DDL from captured MySQL SHOW CREATE TABLE
# Type mapping per docs/reference/database/legacy-schema.md section 7.
import re, sys

SRC = "/tmp/gpg/show_create_all.txt"
OUT = "/tmp/gpg/05-ddl.sql"

PG_RESERVED = {"window","where","when","user","order","group","primary","select","from","to"}

# Columns whose live data violates the MySQL enum definition (imported from the 2026-08-08
# pack dump under non-strict sql_mode; value is '' = enum index 0). Preserve data byte-identical:
# keep text WITHOUT CHECK. Audit: mob_proto.size 2864/2864, setAffectFlag 80, setAffectFlag2 96.
NO_CHECK = {
    ("player", "mob_proto", "size"),
    ("player", "skill_proto", "setAffectFlag"),
    ("player", "skill_proto", "setAffectFlag2"),
}

def q(name):
    return '"' + name + '"' if name in PG_RESERVED else name

def map_type(mtype, unsigned):
    mtype = mtype.strip()
    m = re.match(r"^enum\((.*)\)$", mtype)
    if m:
        vals = re.findall(r"'([^']*)'", m.group(1))
        return ("text", vals, "enum")
    m = re.match(r"^set\((.*)\)$", mtype)
    if m:
        vals = re.findall(r"'([^']*)'", m.group(1))
        return ("text", vals, "set")
    if mtype == "float":
        return ("real", None, "plain")
    if mtype == "datetime":
        return ("timestamp without time zone", None, "plain")
    if mtype == "timestamp":
        return ("timestamp without time zone", None, "plain")
    m = re.match(r"^varchar\((\d+)\)$", mtype)
    if m:
        return (f"varchar({m.group(1)})", None, "plain")
    m = re.match(r"^varbinary\((\d+)\)$", mtype)
    if m:
        return ("bytea", None, "bytea")
    if mtype in ("tinyblob", "blob", "mediumblob", "longblob", "binary"):
        return ("bytea", None, "bytea")
    m = re.match(r"^int(?:\(\d+\))?$", mtype)
    if m:
        return ("bigint" if unsigned else "integer", None, "plain")
    m = re.match(r"^tinyint(?:\(\d+\))?$", mtype)
    if m:
        return ("smallint", None, "plain")
    m = re.match(r"^smallint(?:\(\d+\))?$", mtype)
    if m:
        return ("integer" if unsigned else "smallint", None, "plain")
    m = re.match(r"^mediumint(?:\(\d+\))?$", mtype)
    if m:
        return ("bigint" if unsigned else "integer", None, "plain")
    m = re.match(r"^bigint(?:\(\d+\))?$", mtype)
    if m:
        return ("numeric(20,0)" if unsigned else "bigint", None, "plain")
    raise ValueError(f"unmapped type: {mtype}")

def trans_default(dflt, kind):
    dflt = dflt.strip()
    if dflt == "NULL":
        return "DEFAULT NULL"
    if dflt == "current_timestamp()":
        return "DEFAULT now()"
    if dflt.startswith("'") and dflt.endswith("'"):
        s = dflt[1:-1]
        if kind == "bytea":
            return f"DEFAULT '{s}'::bytea"
        return f"DEFAULT '{s}'"
    # numeric or negative numeric or expression
    return f"DEFAULT {dflt}"

def parse_block(block):
    lines = block.split("\n")
    header = lines[0]
    m = re.match(r"===== (\w+)\.(\w+) =====", header)
    db, tbl = m.group(1), m.group(2)
    cols, keys, ai = [], [], None
    for ln in lines[1:]:
        ln = ln.strip()
        if ln.startswith("`"):
            # column definition
            m = re.match(r"^`(\w+)`\s+(.+?)(?:,)?$", ln)
            colname, rest = m.group(1), m.group(2)
            rest = rest.strip().rstrip(",")
            # split off COMMENT
            comment = None
            cm = re.search(r"COMMENT '(.*?)'$", rest)
            if cm:
                comment = cm.group(1)
                rest = rest[:cm.start()].strip().rstrip(",").strip()
            # type + optional unsigned + modifiers
            tm = re.match(r"^(\S+(?:\([^)]*\))?)\s*(unsigned)?\s*(.*)$", rest)
            mtype, unsigned, mods = tm.group(1), bool(tm.group(2)), tm.group(3).strip()
            pgtype, enumvals, kind = map_type(mtype, unsigned)
            notnull = "NOT NULL" if "NOT NULL" in mods else ""
            dflt = ""
            dm = re.search(r"DEFAULT\s+(.+?)$", mods)
            if dm:
                dflt = trans_default(dm.group(1), kind)
            is_ai = "AUTO_INCREMENT" in mods
            colsql = f"  {q(colname)} {pgtype}"
            if is_ai:
                colsql += " GENERATED BY DEFAULT AS IDENTITY"
            if notnull:
                colsql += " NOT NULL"
            if dflt:
                colsql += " " + dflt
            cols.append((colname, colsql, enumvals, kind, comment, is_ai))
        elif ln.startswith("PRIMARY KEY"):
            m = re.match(r"PRIMARY KEY \(`([^)]+)`\)", ln)
            cols2 = ", ".join(q(c.strip()) for c in m.group(1).split("`,`"))
            keys.append(("PK", f"  PRIMARY KEY ({cols2})"))
        elif ln.startswith("UNIQUE KEY"):
            m = re.match(r"UNIQUE KEY `(\w+)` \(`([^)]+)`\)", ln)
            cols2 = ", ".join(q(c.strip()) for c in m.group(2).split("`,`"))
            keys.append(("UQ", f"  UNIQUE ({cols2})"))
        elif ln.startswith("KEY"):
            m = re.match(r"KEY `(\w+)` \(`([^)]+)`\)", ln)
            cols2 = ", ".join(q(c.strip()) for c in m.group(2).split("`,`"))
            keys.append(("IX", (m.group(1), cols2)))
        elif ln.startswith("ENGINE=") or ln.startswith(")"):
            am = re.search(r"AUTO_INCREMENT=(\d+)", ln)
            if am:
                ai = int(am.group(1))
    return db, tbl, cols, keys, ai

def main():
    with open(SRC, encoding="utf-8", errors="replace") as f:
        text = f.read()
    blocks = re.split(r"^===== ", text, flags=re.M)
    out = []
    out.append("-- Generated by gen_ddl.py from live MariaDB SHOW CREATE TABLE (2026-08-10)")
    out.append("-- Mapping per docs/reference/database/legacy-schema.md \u00a77 (unsigned->bigint, enum/set->text, varbinary->bytea, datetime->timestamp)")
    for b in blocks:
        if not b.strip():
            continue
        b = "===== " + b
        db, tbl, cols, keys, ai = parse_block(b)
        out.append(f"\n-- ===== {db}.{tbl} =====")
        out.append(f"DROP TABLE IF EXISTS {db}.{tbl} CASCADE;")
        out.append(f"CREATE TABLE {db}.{tbl} (")
        body = []
        for (colname, colsql, enumvals, kind, comment, is_ai) in cols:
            body.append(colsql)
            if enumvals is not None and kind == "enum" and (db, tbl, colname) not in NO_CHECK:
                vals = ", ".join(f"'{v}'" for v in enumvals)
                body[-1] += f" CHECK ({q(colname)} IN ({vals}))"
        for (ktype, ksql) in keys:
            if ktype != "IX":
                body.append(ksql)
        out.append(",\n".join(body))
        out.append(");")
        for (ktype, ksql) in keys:
            if ktype == "IX":
                name, cols2 = ksql
                out.append(f"CREATE INDEX {q(name)} ON {db}.{tbl} ({cols2});")
        for (colname, colsql, enumvals, kind, comment, is_ai) in cols:
            if comment:
                out.append(f"COMMENT ON COLUMN {db}.{tbl}.{q(colname)} IS '{comment.replace(chr(39), chr(39)+chr(39))}';")
        if ai:
            out.append(f"-- seed: next identity value = {ai}")
            out.append(f"SELECT setval(pg_get_serial_sequence('{db}.{tbl}', 'id'), {ai - 1}, true);")
            # note: pg_get_serial_sequence works with identity columns (PG>=10)
    with open(OUT, "w", encoding="utf-8") as f:
        f.write("\n".join(out) + "\n")
    print(f"wrote {OUT}")
    print(f"tables: {len([l for l in out if l.startswith('CREATE TABLE')])}")

if __name__ == "__main__":
    main()
