-- Phase land (2026-08-28): identidad de player.land desde PG — la sequence
-- sustituye al AtomicU32 del stub (game_core::land). Verificado contra el PG
-- vivo: id es `GENERATED BY DEFAULT AS IDENTITY` y su sequence es
-- `player.land_id_seq` (pg_get_serial_sequence) — 108 filas, max(id) 292,
-- last_value 292, is_called t (el próximo nextval da 293). Idempotente.
CREATE SEQUENCE IF NOT EXISTS player.land_id_seq;
SELECT setval('player.land_id_seq', COALESCE((SELECT max(id) FROM player.land), 1));