-- ============================================================================
-- migrate_guild_tables.sql — G-PG follow-up (F3 tail lane, 2026-08-13)
--
-- Gap cerrado: `player.guild_member`, `player.guild_grade`,
-- `player.guild_comment` NO existian en PG (verificado pg_catalog
-- 2026-08-13; documentado en database/src/social.rs). `player.guild` y
-- `player.guild_war_reservation` ya estaban migrados.
--
-- Fuente de datos: MariaDB archivado
--   C:\projects\metin2-extra\archive\mariadb_full_2026-08-12.sql
--   (mysqldump 10.11.18, --hex-blob; el dump contiene las tablas DOS veces:
--   db `player` L4184-4298 y db `srv1_player` L21857-21971 — copia identica,
--   ambas VACIAS). CREATE de referencia: L4273-4288 (guild_member),
--   L4248-4262 (guild_grade), L4219-4237 (guild_comment).
--
-- DATOS: las secciones "Dumping data" de las 3 tablas NO contienen INSERTs
-- (solo LOCK TABLES / DISABLE KEYS / ENABLE KEYS / UNLOCK — L4239-4246,
-- L4264-4271, L4291-4298). Filas origen = 0 en cada tabla. La migracion es
-- SOLO de esquema; no hay datos que cargar.
--
-- Adaptacion de tipos (convenciones legacy-schema.md §7, igual que el G-PG):
--   int unsigned       -> bigint
--   tinyint            -> smallint
--   set('A','B',...)   -> text + CHECK (col = ANY (ARRAY[...]))
--                        (mismo patron que player.land.land_enable_check)
--   datetime           -> timestamp
--   AUTO_INCREMENT     -> GENERATED BY DEFAULT AS IDENTITY
--   cero fechas        -> NULL (n/a aqui: las columnas time ya son NULL-ables)
--
-- Decisiones documentadas:
--   - guild_grade.auth: se PRESERVA el typo legacy `REMOVE_MEMEBER` del SET
--     (documentado en docs/reference/database/legacy-schema.md §5 — el C++
--     escribe ese valor literal, guild.cpp:106/838). El CHECK acepta NULL,
--     '' (bitmask 0) y cualquier subconjunto separado por comas de los 4
--     literales (semantica del SET de MariaDB: el juego escribe auth como
--     bitmask `%d` y MariaDB lo guarda como string comma-joined — guild.cpp:
--     106/838; el orden NO se restringe: MariaDB canonicaliza, pero el port
--     Rust futuro no debe poder escribir basura fuera del alfabeto).
--   - guild_comment.id: identity, porque el juego inserta comentarios SIN id
--     (guild.cpp:1014 `INSERT INTO guild_comment(guild_id, name, notice,
--     content, time)`) y el legacy dependia del AUTO_INCREMENT.
--   - guild_member: UNIQUE (pid) — constraint real del legacy (un jugador
--     solo puede pertenecer a una guild; UNIQUE KEY `pid` L4287).
--   - Index secundario: guild_comment(guild_id) (KEY `guild_id` legacy). El
--     KEY `aaa` (notice,id,guild_id) es un hint de la era MySQL; la query del
--     port futuro (`WHERE guild_id=? ORDER BY notice DESC, id DESC LIMIT N`,
--     guild.cpp:1045) se expresara con el index del port — no se replica.
--   - Sin FOREIGN KEYs: el legacy no tenia (claves app-level), y el G-PG
--     tampoco las migro (verificado: 0 FKs en todo el esquema migrado).
--
-- Re-runnable: CREATE TABLE IF NOT EXISTS + CREATE UNIQUE INDEX IF NOT EXISTS.
-- ============================================================================

-- ----------------------------------------------------------------------------
-- player.guild_member — PK (guild_id, pid); UNIQUE pid
-- (MariaDB L4273-4288: pid int unsigned, guild_id int unsigned, grade
--  tinyint(2) NULL, is_general tinyint(1) NOT NULL 0, offer int unsigned NULL)
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS player.guild_member (
    pid        bigint   NOT NULL DEFAULT 0,
    guild_id   bigint   NOT NULL DEFAULT 0,
    grade      smallint          DEFAULT NULL,
    is_general smallint NOT NULL DEFAULT 0,
    offer      bigint            DEFAULT NULL,
    PRIMARY KEY (guild_id, pid)
);

CREATE UNIQUE INDEX IF NOT EXISTS guild_member_pid_key
    ON player.guild_member (pid);

-- ----------------------------------------------------------------------------
-- player.guild_grade — PK (guild_id, grade)
-- (MariaDB L4248-4262: guild_id int unsigned, grade tinyint(4) NOT NULL 0,
--  name varchar(12) NOT NULL '', auth set(...) NULL)
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS player.guild_grade (
    guild_id bigint NOT NULL DEFAULT 0,
    grade    smallint NOT NULL DEFAULT 0,
    name     varchar(12) NOT NULL DEFAULT '',
    auth     text DEFAULT NULL,
    PRIMARY KEY (guild_id, grade),
    CONSTRAINT guild_grade_auth_check CHECK (
        auth IS NULL
        OR auth = ''
        OR auth ~ '^(ADD_MEMBER|REMOVE_MEMEBER|NOTICE|USE_SKILL)(,(ADD_MEMBER|REMOVE_MEMEBER|NOTICE|USE_SKILL))*$'
    )
);

-- ----------------------------------------------------------------------------
-- player.guild_comment — PK id (identity)
-- (MariaDB L4219-4237: id int unsigned AI, guild_id int unsigned NULL,
--  name varchar(24) NULL, notice tinyint(4) NULL, content varchar(50) NULL,
--  time datetime NULL; KEY aaa(notice,id,guild_id), KEY guild_id(guild_id))
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS player.guild_comment (
    id       bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    guild_id bigint            DEFAULT NULL,
    name     varchar(24)       DEFAULT NULL,
    notice   smallint          DEFAULT NULL,
    content  varchar(50)       DEFAULT NULL,
    time     timestamp         DEFAULT NULL
);

CREATE INDEX IF NOT EXISTS guild_comment_guild_id_idx
    ON player.guild_comment (guild_id);

-- ----------------------------------------------------------------------------
-- Verificacion (psql):
--   SELECT 'guild_member' t, count(*) FROM player.guild_member
--   UNION ALL SELECT 'guild_grade', count(*) FROM player.guild_grade
--   UNION ALL SELECT 'guild_comment', count(*) FROM player.guild_comment;
--   -- esperado 0 / 0 / 0 (fuente MariaDB vacia, ver cabecera)
--
--   -- huerfanos (guild_id sin guild padre; esperado 0):
--   SELECT count(*) FROM player.guild_member m
--   LEFT JOIN player.guild g ON g.id = m.guild_id
--   WHERE g.id IS NULL;
--
--   -- CHECK de auth (semantica SET: subconjuntos comma-joined, '', NULL):
--   BEGIN;
--   INSERT INTO player.guild_grade (guild_id, grade, name, auth)
--   VALUES (1,1,'a','NOTICE,USE_SKILL'), (1,2,'b',''), (1,3,'c',NULL);
--   ROLLBACK;  -- acepta (3 filas)
--   BEGIN;
--   INSERT INTO player.guild_grade (guild_id, grade, name, auth)
--   VALUES (1,9,'z','BOGUS');
--   ROLLBACK;  -- ERROR: viola guild_grade_auth_check
-- ============================================================================
